name: load-tests
description: "Run load tests"

runs:
  using: "composite"
  steps:
    - name: Run local k6 test
      #grafana/k6-action@0.3.0
      uses: grafana/k6-action@2bd221c807b7cdbe4bb3abc6b3fa4d2da499fa9b
      with:
        filename: load-tests/04-request-response.js