name: load-tests
description: "Run load tests"

inputs:
  test_name:
    description: "Test to be executed"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run local k6 test
      #grafana/k6-action@0.3.0
      uses: grafana/k6-action@2bd221c807b7cdbe4bb3abc6b3fa4d2da499fa9b
      working-directory: ./load-tests
      with:
        filename: ${{ inputs.test_name }}