name: "Load-Tests"

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Choose load test'
        type: choice
        required: true
        default: dev
        options:
        - 01-metadata.js
        - 02-requests.js
        - 03-response.js
        - 04-request-response.js
        - 05-metadata-request-response.js
        - 06-breakpoint-metadata-request-response.js
        

permissions:
  contents: read

jobs:
  k6-load-tests-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    name: load-tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        #actions/checkout@3.2.0
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Load tests
        uses: ./.github/workflows/load-tests
        with:
          test_name : ${{ inputs.test_name }}